export const WORDS = [
  'AGENT',
  'WORLD',
  'ABOUT',
  'HEART',
  'WATER',
  'SIXTY',
  'BOARD',
  'MONTH',
  'MUSIC',
  'PARTY',
  'PIANO',
  'MOUTH',
  'WOMAN',
  'SUGAR',
  'AMBER',
  'DREAM',
  'LAUGH',
  'TIGER',
  'EARTH',
  'MONEY',
  'WORDS',
  'SMILE',
  'LEMON',
  'SOUTH',
  'AFTER',
  'STONE',
  'THING',
  'LIGHT',
  'STORY',
  'POWER',
  'TODAY',
  'RANGE',
  'PEARL',
  'VENOM',
  'PROXY',
  'ROUND',
  'HOVER',
  'CANDY',
  'ABOVE',
  'PHONE',
  'OTHER',
  'SMART',
  'BLACK',
  'MAGIC',
  'FRUIT',
  'RADIO',
  'ROYAL',
  'HONEY',
  'FLAKE',
  'SOUND',
];


export const keyboardLetters = [
  { letter: 'Q', status: 'unused' },
  { letter: 'W', status: 'unused' },
  { letter: 'E', status: 'unused' },
  { letter: 'R', status: 'unused' },
  { letter: 'T', status: 'unused' },
  { letter: 'Y', status: 'unused' },
  { letter: 'U', status: 'unused' },
  { letter: 'I', status: 'unused' },
  { letter: 'O', status: 'unused' },
  { letter: 'P', status: 'unused' },
  { letter: 'A', status: 'unused' },
  { letter: 'S', status: 'unused' },
  { letter: 'D', status: 'unused' },
  { letter: 'F', status: 'unused' },
  { letter: 'G', status: 'unused' },
  { letter: 'H', status: 'unused' },
  { letter: 'J', status: 'unused' },
  { letter: 'K', status: 'unused' },
  { letter: 'L', status: 'unused' },
  { letter: 'Z', status: 'unused' },
  { letter: 'X', status: 'unused' },
  { letter: 'C', status: 'unused' },
  { letter: 'V', status: 'unused' },
  { letter: 'B', status: 'unused' },
  { letter: 'N', status: 'unused' },
  { letter: 'M', status: 'unused' }
];